version: '3.8'

services:
  camera_server:
    build: .
    container_name: camera_server
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
